### PR TITLE
Add partitioned column to pgmq_meta

### LINKED ISSUE #91: add 'partitioned' attribute to pgmq_meta
pgmq_meta should have an attribute that tracks whether the queue is partitioned or not. This will be useful when dropping a queue, so we can also cleanup relevant entries in pg_partman. But also for general observability into existing queue.

Does not necessarily need to explicitly be "partitioned" as the attribute name, but some attribute that lets us know how the type of queue when inspecting pgmq_meta. Right now, there are just two types; partitioned and non-partitioned. In the future, there could be several types of partitioning.

### PR DESCRIPTION
**Pull request by craigpastro**
Resolves #91.

I had a go at resolving this.

Oh, I don't know how I should go about updating the `pgmq-rs` crate. Do you publish a new version of `pgmq` then update in a new PR?

Thanks!

### CODE REVIEW

**Review by v0idpwn — COMMENTED** [review]
I think you'd want to provide a migration for this

**Comment by craigpastro** [comment]
> I think you'd want to provide a migration for this

Thanks for your comment! Good idea. But I actually am not sure how I can do this.

One thought: I see partitioned queues have an index that non-partitioned queues do not, so I could try to list those, extract the table name from the index, and update based on that. But that sounds horrific. Maybe I am missing something.

**Comment by ChuckHend** [comment]
> One thought: I see partitioned queues have an index that non-partitioned queues do not, so I could try to list those, extract the table name from the index, and update based on that. But that sounds horrific. Maybe I am missing something.

Maybe something like this? You'd also want to check first that pg_partman exists.

```
SELECT EXISTS(SELECT * FROM public.part_config where parent_table = '{queue_table}');
```

**Comment by craigpastro** [comment]
Added a migration and tested locally if things are fine when pg_partman is installed and when it is not installed. Seems to work. Thanks for the hint!

**Review by ChuckHend — APPROVED** [review]

**Pull request merged**
