### PR TITLE
Remove unnecessary references

### PR DESCRIPTION
**Pull request by pbzweihander**
`i32` and `chrono::DateTime` implement `Copy` trait. We don't need to take reference of it.

### CODE REVIEW

**Review by ChuckHend — APPROVED** [review]
Can you bump the minor version on core/Cargo.toml? Should be good to merge after that.

**Comment by pbzweihander** [comment]
I have updated the version!

**Comment by pbzweihander** [comment]
Oh, Should I leave outer crate's version as-is?

**Comment by ChuckHend** [comment]
> Oh, Should I leave outer crate's version as-is?

We can leave the outer crate as is. I'll do a release after this merges.

Thank you for jumping in a contributing!

**Pull request merged**
