### PR TITLE
Allow pg_partman to be installed in any schema

### LINKED ISSUE #306: pg_partman assumed to be in the public schema
Currently pg_partman is assumed to be in the `public` schema

It's hard coded in several places
https://github.com/tembo-io/pgmq/blob/18465f5f9344b9bcaca8566563d6a628f90bfa9a/pgmq-extension/sql/pgmq.sql#L750
https://github.com/tembo-io/pgmq/blob/18465f5f9344b9bcaca8566563d6a628f90bfa9a/pgmq-extension/sql/pgmq.sql#L764

which prevents `pg_partman` being referenced by `pgmq` if `pg_patman` is installed in e.g. an `extensions` schema

### PR DESCRIPTION
**Pull request by olirice**
Allows pg_partman to be installed in any schema vs hard-coded to `public`

#### New Functions
- pgmq._get_pg_partman_schema()

#### Updated Functions
- pgmq.drop_queue
- pgmq.create_partitioned
- pgmq.convert_archive_partitioned

Resolves #306

### CODE REVIEW

**Review by theory — APPROVED** [review]
I don't think pg_partman is relocatable, so in theory we could set `search_path` in the [CREATE FUNCTION] statements — or just get the schema name at install time and compile it into the functions. But that's probably more of a PITA than it's worth.

**Comment by olirice** [comment]
agreed

Since its an optional dependency, pg_partman could be installed after pgmq. In that case install-time interpolation wouldn't be an option.

**Comment by ChuckHend** [comment]
@olirice , thanks again for this work. 1.4.3 has not yet been released. Did you want this to go out in a separate patch? I'll release 1.4.3 quick if this needs to be in 1.4.4, otherwise could we put the migration sql in https://github.com/tembo-io/pgmq/blob/main/pgmq-extension/sql/pgmq--1.4.2--1.4.3.sql?

**Comment by olirice** [comment]
No preference from me if you'd prefer to put them together. Separate PRs was only for review-ability

**Review by ChuckHend — APPROVED** [review]

**Pull request merged**
