### PR TITLE
feat: overloaded the function to have a custom query

### LINKED ISSUE #288: Feature Request: Conditional reading for PGMQ
I request an enhancement for the PGMQ extension to support conditional message retrieval. This would allow pulling based on specific attributes directly within the pgmq_read function.

eg: Pull messages with a specific type:
`SELECT * FROM pgmq_read('my_queue', 30, 1, '{"type": "A"}');`

Thank you for considering this feature request.

### PR DESCRIPTION
**Pull request by Abiji-2020**
# Overloaded the read function to support the feature. 

closes #288 
/claim #288

### CODE REVIEW

**Comment by Abiji-2020** [comment]
CI is failing due to the differences in the  expected.out and the base.out that is created during test. Will Optmise and update the expected base.out.

**Comment by Abiji-2020** [comment]
image

Even though the values are same, it still shows error and in my local the test are passing
image

**Comment by Neptune650** [comment]
I already submitted a PR for this #322, so I'm not quite sure what's the need for this one.

**Comment by Abiji-2020** [comment]
> I already submitted a PR for this #322, so I'm not quite sure what's the need for this one.

Actually i forgot to mention in the issue, so i just pushed and submited

**Comment by Neptune650** [comment]
This user is known to do plagiarism:
https://github.com/tailcallhq/rust-gh-workflows/pull/12#issuecomment-2425091810

**Comment by Abiji-2020** [comment]
> This user is known to do plagiarism: [tailcallhq/rust-gh-workflows#12 (comment)](https://github.com/tailcallhq/rust-gh-workflows/pull/12#issuecomment-2425091810)

That was a issue to be resolved with them

**Comment by Abiji-2020** [comment]
@ChuckHend could you please review it.?

**Comment by ChuckHend** [comment]
> @ChuckHend could you please review it.?

We are currently reviewing https://github.com/tembo-io/pgmq/pull/322 since it was opened first.

**Comment by ChuckHend** [comment]
Closing this issue. The feature was merged in https://github.com/tembo-io/pgmq/pull/322

**Pull request closed without merging**
