### PR TITLE
fix: deprecated Node.js usage in `checkout@v3`

### LINKED ISSUE #239: CI uses `actions/checkout@v3`, which uses a `deprecated` version of `Node.js`

### PR DESCRIPTION
**Pull request by hamirmahal**
fixes #239.

### CODE REVIEW

**Review by v0idpwn — APPROVED** [review]

**Review by hamirmahal — COMMENTED** [review]
The `PGMQ Extension / Build and push images` failures are from

```
Error: Username and password required
```

when trying to log in to Quay.

**Comment by v0idpwn** [comment]
Thank you! :)

**Comment by v0idpwn** [comment]
I see there a few other uses of checkout@v3 and even v2:

```
.github/workflows/extension_upgrade.yml:      - uses: actions/checkout@v2
.github/workflows/cargo_publish.yml:        uses: actions/checkout@v3
.github/workflows/cargo_publish.yml:        uses: actions/checkout@v3
.github/workflows/core.yml:      - uses: actions/checkout@v3
.github/workflows/core.yml:      - uses: actions/checkout@v2
.github/workflows/crate_ci.yml:      - uses: actions/checkout@v3
.github/workflows/crate_ci.yml:      - uses: actions/checkout@v2
.github/workflows/pgmq_python.yml:    - uses: actions/checkout@v2
.github/workflows/pgmq_python.yml:    - uses: actions/checkout@v2
.github/workflows/pgmq_python.yml:    - uses: actions/checkout@v2
.github/workflows/extension_ci.yml:      - uses: actions/checkout@v3
.github/workflows/extension_ci.yml:      - uses: actions/checkout@v2
.github/workflows/extension_ci.yml:      - uses: actions/checkout@v2
.github/workflows/extension_ci.yml:        uses: actions/checkout@v3
.github/workflows/pgxn-release.yml:      uses: actions/checkout@v4
```

Would gladly accept another PR updating those to v4 too, otherwise I can bump them later

**Comment by hamirmahal** [comment]
You're welcome!

**Comment by hamirmahal** [comment]
I might be able to take a look at those tomorrow.

**Pull request merged**
