### PR TITLE
pgmq-core - make the `enqueue` method return a parametrized query

### PR DESCRIPTION
**Pull request by nimrodkor**
Part #1 of 2 for #185 - this enhnaces the core so it will generate a parametrized query allowing sqlx / pg to do the sanitization of the input

### CODE REVIEW

**Comment by ChuckHend** [comment]
`pgmq-rs` deploys on merge to main. So some of the CI checks will fail if the Cargo.toml version already exists in crates.io. I think bumping this to 0.26.1 should work.

https://github.com/tembo-io/pgmq/blob/6ea785593a740e97fe277311a0e4d6c36ca1fe20/pgmq-rs/Cargo.toml#L3

**Comment by nimrodkor** [comment]
This is in `core` so bumped it to 0.8.4

**Comment by nimrodkor** [comment]
@ChuckHend mind giving the CI an approve?

**Comment by nimrodkor** [comment]
Not sure I can fix this one:
image
@ChuckHend

**Comment by ChuckHend** [comment]
sorry @nimrodkor, I merged main back into this branch. We'll need to bump it to `core` to 0.8.5 now.

**Review by ChuckHend — APPROVED** [review]

**Pull request merged**
